Repository blockchain/blockchain-wallet-v4-frontend, pull requests merged in 2019-01, with the labels that each got.

#1293 Matomo
  packages/blockchain-wallet-v4-frontend/src/data/analytics/actionTypes.js
  packages/blockchain-wallet-v4-frontend/src/data/analytics/actions.js
  packages/blockchain-wallet-v4-frontend/src/data/analytics/model.js
  packages/blockchain-wallet-v4-frontend/src/data/analytics/reducers.js
  packages/blockchain-wallet-v4-frontend/src/data/analytics/reducers.spec.js
  packages/blockchain-wallet-v4-frontend/src/data/analytics/sagaRegister.js
  packages/blockchain-wallet-v4-frontend/src/data/analytics/sagas.js
  packages/blockchain-wallet-v4-frontend/src/data/analytics/sagas.spec.js
  packages/blockchain-wallet-v4-frontend/src/data/analytics/selectors.js
  packages/blockchain-wallet-v4-frontend/src/data/auth/sagas.js
  packages/blockchain-wallet-v4-frontend/src/data/auth/sagas.spec.js
  packages/blockchain-wallet-v4-frontend/src/data/components/exchange/exchange.sagas.js
  packages/blockchain-wallet-v4-frontend/src/data/components/identityVerification/sagas.js
  packages/blockchain-wallet-v4-frontend/src/data/components/onfido/sagas.js
  packages/blockchain-wallet-v4-frontend/src/data/components/onfido/sagas.spec.js
  packages/blockchain-wallet-v4-frontend/src/data/components/sendBtc/model.js
  packages/blockchain-wallet-v4-frontend/src/data/components/sendBtc/sagas.js
  packages/blockchain-wallet-v4-frontend/src/data/components/sendBtc/sagas.spec.js
  packages/blockchain-wallet-v4-frontend/src/data/components/veriff/sagas.js
  packages/blockchain-wallet-v4-frontend/src/data/components/veriff/sagas.spec.js
  packages/blockchain-wallet-v4-frontend/src/data/modules/sfox/sagas.js
  packages/blockchain-wallet-v4-frontend/src/data/rootReducer.js
  packages/blockchain-wallet-v4-frontend/src/data/selectors.js
  packages/blockchain-wallet-v4-frontend/src/layouts/Public/index.js
  packages/blockchain-wallet-v4-frontend/src/layouts/Wallet/MenuLeft/Navigation/index.js
  packages/blockchain-wallet-v4-frontend/src/layouts/Wallet/MenuLeft/Navigation/template.js
  packages/blockchain-wallet-v4-frontend/src/layouts/Wallet/MenuTop/Actions/index.js
  packages/blockchain-wallet-v4-frontend/src/layouts/Wallet/MenuTop/Actions/selectors.js
  packages/blockchain-wallet-v4-frontend/src/layouts/Wallet/template.js
  packages/blockchain-wallet-v4-frontend/src/modals/Exchange/IdentityVerification/Veriff/index.js
  packages/blockchain-wallet-v4-frontend/src/modals/Lockbox/LockboxSetup/ConnectDeviceStep/index.js
  packages/blockchain-wallet-v4-frontend/src/modals/Lockbox/LockboxSetup/ErrorStep/index.js
  packages/blockchain-wallet-v4-frontend/src/modals/Lockbox/LockboxSetup/NameDeviceStep/index.js
  packages/blockchain-wallet-v4-frontend/src/modals/Lockbox/LockboxSetup/OpenBtcAppStep/index.js
  packages/blockchain-wallet-v4-frontend/src/modals/Onfido/index.js
  packages/blockchain-wallet-v4-frontend/src/modals/Sfox/SfoxExchangeData/index.js
  packages/blockchain-wallet-v4-frontend/src/providers/AnalyticsTracker/index.js
  packages/blockchain-wallet-v4-frontend/src/scenes/Exchange/ExchangeConfirm/index.js
  packages/blockchain-wallet-v4-frontend/src/scenes/Exchange/ExchangeForm/index.js
  packages/blockchain-wallet-v4-frontend/src/scenes/Exchange/index.js
  packages/blockchain-wallet-v4/src/network/api/analytics/index.js
  packages/blockchain-wallet-v4/src/redux/data/sfox/sagas.js
Labels: don't merge yet

#876 Update lifecycle methods
  packages/blockchain-info-components/src/Carousels/Carousel/index.js
  packages/blockchain-info-components/src/Footer/Select/Select.js
  packages/blockchain-info-components/src/Form/SelectInput/index.js
  packages/blockchain-wallet-v4-frontend/src/assets/locales/hu.json
  packages/blockchain-wallet-v4-frontend/src/assets/locales/zh_CN.json
  packages/blockchain-wallet-v4-frontend/src/components/Form/CaptchaBox/index.js
  packages/blockchain-wallet-v4-frontend/src/layouts/Wallet/MenuTop/Balance/WalletBalance/BchBalance/index.js
  packages/blockchain-wallet-v4-frontend/src/layouts/Wallet/MenuTop/Balance/WalletBalance/BtcBalance/index.js
  packages/blockchain-wallet-v4-frontend/src/layouts/Wallet/MenuTop/Balance/WalletBalance/EthBalance/index.js
  packages/blockchain-wallet-v4-frontend/src/layouts/Wallet/MenuTop/Balance/WatchOnlyBalance/BchWatchOnlyBalance/index.js
  packages/blockchain-wallet-v4-frontend/src/layouts/Wallet/MenuTop/Balance/WatchOnlyBalance/BtcWatchOnlyBalance/index.js
  packages/blockchain-wallet-v4-frontend/src/modals/Bch/RequestBch/index.js
  packages/blockchain-wallet-v4-frontend/src/modals/Btc/RequestBtc/FirstStep/index.js
  packages/blockchain-wallet-v4-frontend/src/modals/Coinify/CoinifyExchangeData/Confirm/index.js
  packages/blockchain-wallet-v4-frontend/src/modals/Coinify/CoinifyExchangeData/Create/AcceptTerms/index.js
  packages/blockchain-wallet-v4-frontend/src/modals/Eth/RequestEth/index.js
  packages/blockchain-wallet-v4-frontend/src/modals/Lockbox/LockboxFirmware/index.js
  packages/blockchain-wallet-v4-frontend/src/modals/RecoveryPhrase/ThirdStep/index.js
  packages/blockchain-wallet-v4-frontend/src/modals/RecoveryPhrase/index.js
  packages/blockchain-wallet-v4-frontend/src/modals/Sfox/SfoxExchangeData/Verify/index.js
  packages/blockchain-wallet-v4-frontend/src/modals/Wallet/PairingCode/index.js
  packages/blockchain-wallet-v4-frontend/src/modals/Xlm/RequestXlm/index.js
  packages/blockchain-wallet-v4-frontend/src/scenes/BuySell/CoinifyCheckout/Content/OrderCheckout.js
  packages/blockchain-wallet-v4-frontend/src/scenes/BuySell/ExchangeCheckout/index.js
  packages/blockchain-wallet-v4-frontend/src/scenes/BuySell/SfoxCheckout/Content/OrderCheckout.js
  packages/blockchain-wallet-v4-frontend/src/scenes/BuySell/SfoxCheckout/Content/OrderReview.js
  packages/blockchain-wallet-v4-frontend/src/scenes/Goals/index.js
  packages/blockchain-wallet-v4-frontend/src/scenes/Home/DidYouKnow/index.js
  packages/blockchain-wallet-v4-frontend/src/scenes/Lockbox/index.js
  packages/blockchain-wallet-v4-frontend/src/scenes/Recover/index.js
  packages/blockchain-wallet-v4-frontend/src/scenes/Reset2FA/index.js
  packages/blockchain-wallet-v4-frontend/src/scenes/SecurityCenter/AdvancedSecurity/IPWhitelist/Settings/index.js
  packages/blockchain-wallet-v4-frontend/src/scenes/SecurityCenter/BasicSecurity/TwoStepVerification/GoogleAuth/index.js
  packages/blockchain-wallet-v4-frontend/src/scenes/SecurityCenter/BasicSecurity/WalletRecoveryPhrase/RecordBackupPhrase/ThirdStep/index.js
  packages/blockchain-wallet-v4-frontend/src/scenes/SecurityCenter/BasicSecurity/WalletRecoveryPhrase/RecordBackupPhrase/index.js
  packages/blockchain-wallet-v4-frontend/src/scenes/SecurityCenter/BasicSecurity/WalletRecoveryPhrase/index.js
  packages/blockchain-wallet-v4-frontend/src/scenes/Settings/Addresses/Btc/ManageAddresses/UnusedAddresses/index.js
  packages/blockchain-wallet-v4-frontend/src/scenes/Settings/Addresses/Btc/ManageAddresses/UsedAddresses/Table/index.js
  packages/blockchain-wallet-v4-frontend/src/scenes/Settings/Preferences/AutoLogout/Settings/EditForm/index.js
  packages/blockchain-wallet-v4-frontend/src/scenes/Settings/Preferences/LocalCurrency/Settings/index.js
  packages/blockchain-wallet-v4-frontend/src/scenes/Settings/Preferences/Themes/Settings/index.js
  packages/blockchain-wallet-v4-frontend/src/scenes/Settings/Preferences/WalletLanguage/Settings/index.js
  packages/blockchain-wallet-v4/src/redux/payment/bch/sagas.js
Labels: tech debt, work in progress

#1247 Feat(Remove Redux-ui)
  config/mocks/wallet-options-v4.json
  packages/blockchain-wallet-v4-frontend/package.json
  packages/blockchain-wallet-v4-frontend/src/components/DropdownLanguage/index.js
  packages/blockchain-wallet-v4-frontend/src/components/StepIndicator/index.js
  packages/blockchain-wallet-v4-frontend/src/data/components/btcTransactions/sagas.spec.js
  packages/blockchain-wallet-v4-frontend/src/data/components/sendBtc/sagas.js
  packages/blockchain-wallet-v4-frontend/src/data/components/sendBtc/sagas.spec.js
  packages/blockchain-wallet-v4-frontend/src/data/modules/securityCenter/sagas.js
  packages/blockchain-wallet-v4-frontend/src/data/modules/settings/sagas.js
  packages/blockchain-wallet-v4-frontend/src/data/rootReducer.js
  packages/blockchain-wallet-v4-frontend/src/modals/Coinify/CoinifyExchangeData/Confirm/index.js
  packages/blockchain-wallet-v4-frontend/src/modals/Coinify/CoinifyExchangeData/Confirm/template.js
  packages/blockchain-wallet-v4-frontend/src/modals/Coinify/CoinifyExchangeData/Create/AcceptTerms/index.js
  packages/blockchain-wallet-v4-frontend/src/modals/Coinify/CoinifyExchangeData/Create/AcceptTerms/template.js
  packages/blockchain-wallet-v4-frontend/src/modals/Coinify/CoinifyExchangeData/Create/VerifyEmail/index.js
  packages/blockchain-wallet-v4-frontend/src/modals/Coinify/CoinifyExchangeData/Create/VerifyEmail/template.js
  packages/blockchain-wallet-v4-frontend/src/modals/Coinify/CoinifyExchangeData/Create/index.js
  packages/blockchain-wallet-v4-frontend/src/modals/Coinify/CoinifyExchangeData/Create/template.js
  packages/blockchain-wallet-v4-frontend/src/modals/Sfox/SfoxExchangeData/Create/AcceptTerms.js
  packages/blockchain-wallet-v4-frontend/src/modals/Sfox/SfoxExchangeData/Create/VerifyEmail.js
  packages/blockchain-wallet-v4-frontend/src/modals/Sfox/SfoxExchangeData/Create/VerifyMobile.js
  packages/blockchain-wallet-v4-frontend/src/modals/Sfox/SfoxExchangeData/Create/index.js
  packages/blockchain-wallet-v4-frontend/src/modals/Sfox/SfoxExchangeData/Create/template.js
  packages/blockchain-wallet-v4-frontend/src/modals/Sfox/SfoxExchangeData/Link/template.js
  packages/blockchain-wallet-v4-frontend/src/modals/Sfox/SfoxExchangeData/Upload/camera.js
  packages/blockchain-wallet-v4-frontend/src/modals/Sfox/SfoxExchangeData/Upload/index.js
  packages/blockchain-wallet-v4-frontend/src/modals/Sfox/SfoxExchangeData/Verify/Address.js
  packages/blockchain-wallet-v4-frontend/src/modals/Sfox/SfoxExchangeData/Verify/Identity.js
  packages/blockchain-wallet-v4-frontend/src/modals/Sfox/SfoxExchangeData/Verify/index.js
  packages/blockchain-wallet-v4-frontend/src/modals/Sfox/SfoxExchangeData/index.js
  packages/blockchain-wallet-v4-frontend/src/scenes/BuySell/index.js
  packages/blockchain-wallet-v4-frontend/src/scenes/BuySell/template.js
  packages/blockchain-wallet-v4-frontend/src/scenes/SecurityCenter/BasicSecurity/WalletRecoveryPhrase/index.js
  packages/blockchain-wallet-v4-frontend/src/services/FormHelper/index.spec.js
  packages/blockchain-wallet-v4-frontend/src/services/FormHelper/normalizers.js
  packages/blockchain-wallet-v4-frontend/src/services/ValidationHelper/index.js
  packages/blockchain-wallet-v4-frontend/src/store/index.js
  packages/blockchain-wallet-v4/src/redux/payment/bch/sagas.js
  yarn.lock
Labels: tech debt

#1103 refactor(API): fetch=>axios
  packages/blockchain-wallet-v4-frontend/src/components/Form/FiatConvertor/Convertor/template.js
  packages/blockchain-wallet-v4-frontend/src/components/Form/SelectBox/index.js
  packages/blockchain-wallet-v4-frontend/src/components/Form/TextBox/index.js
  packages/blockchain-wallet-v4-frontend/src/components/TransactionListItem/template.js
  packages/blockchain-wallet-v4-frontend/src/data/auth/sagas.js
  packages/blockchain-wallet-v4-frontend/src/data/auth/sagas.spec.js
  packages/blockchain-wallet-v4-frontend/src/modals/Btc/RequestBtc/FirstStep/selectors.js
  packages/blockchain-wallet-v4-frontend/src/modals/Btc/RequestBtc/FirstStep/template.success.js
  packages/blockchain-wallet-v4-frontend/src/scenes/SecurityCenter/BasicSecurity/EmailAddress/template.success.js
  packages/blockchain-wallet-v4/src/network/api/fetch.js
  packages/blockchain-wallet-v4/src/network/api/http.js
  packages/blockchain-wallet-v4/src/network/api/index.js
  packages/blockchain-wallet-v4/src/network/api/kvStore/index.js
  packages/blockchain-wallet-v4/src/network/api/lockbox/index.js
  packages/blockchain-wallet-v4/src/network/api/misc/index.js
  packages/blockchain-wallet-v4/src/network/api/settings/index.js
  packages/blockchain-wallet-v4/src/network/api/wallet/index.js
  packages/blockchain-wallet-v4/src/redux/payment/btc/sagas.js
  packages/blockchain-wallet-v4/src/types/Wallet.js
  packages/blockchain-wallet-v4/src/types/util.js
  packages/blockchain-wallet-v4/src/walletCrypto/utils.js
Labels: tech debt
