Repository blockchain/blockchain-wallet-v4-frontend, pull requests merged in 2021-02, with the labels that each got.

#2814 fix(bech32): add test case for correct bech32 pubkeyhash decoding
  packages/blockchain-wallet-v4/src/utils/btc.spec.js
Labels: don't merge yet

#2728 feat(recovery): Store and load wallet credentials in metadata
  packages/blockchain-wallet-v4-frontend/src/data/auth/sagas.js
  packages/blockchain-wallet-v4-frontend/src/data/wallet/sagas.js
  packages/blockchain-wallet-v4-frontend/webpack.config.ci.js
  packages/blockchain-wallet-v4/src/redux/kvStore/actionTypes.js
  packages/blockchain-wallet-v4/src/redux/kvStore/actions.js
  packages/blockchain-wallet-v4/src/redux/kvStore/config.js
  packages/blockchain-wallet-v4/src/redux/kvStore/middleware.js
  packages/blockchain-wallet-v4/src/redux/kvStore/reducers.js
  packages/blockchain-wallet-v4/src/redux/kvStore/sagaRegister.js
  packages/blockchain-wallet-v4/src/redux/kvStore/sagas.js
  packages/blockchain-wallet-v4/src/redux/kvStore/selectors.js
  packages/blockchain-wallet-v4/src/redux/kvStore/walletCredentials/actionTypes.js
  packages/blockchain-wallet-v4/src/redux/kvStore/walletCredentials/actions.js
  packages/blockchain-wallet-v4/src/redux/kvStore/walletCredentials/reducers.js
  packages/blockchain-wallet-v4/src/redux/kvStore/walletCredentials/sagaRegister.js
  packages/blockchain-wallet-v4/src/redux/kvStore/walletCredentials/sagas.js
  packages/blockchain-wallet-v4/src/redux/kvStore/walletCredentials/selectors.js
  packages/blockchain-wallet-v4/src/redux/wallet/sagas.ts
Labels: don't merge yet, work in progress

#2914 feat(mobile auth): Secure channel login
  .release-it.json
  config/mocks/wallet-options-v4.json
  package.json
  packages/blockchain-info-components/src/Dropdowns/SimpleDropdown/template.js
  packages/blockchain-info-components/src/Icons/Icomoon.ts
  packages/blockchain-info-components/src/Images/img/qr-logo.svg
  packages/blockchain-wallet-v4-frontend/package.json
  packages/blockchain-wallet-v4-frontend/src/assets/locales/index.d.ts
  packages/blockchain-wallet-v4-frontend/src/components/QRCodeWrapper/index.tsx
  packages/blockchain-wallet-v4-frontend/src/data/actions.ts
  packages/blockchain-wallet-v4-frontend/src/data/auth/actionTypes.js
  packages/blockchain-wallet-v4-frontend/src/data/auth/actions.js
  packages/blockchain-wallet-v4-frontend/src/data/auth/reducers.js
  packages/blockchain-wallet-v4-frontend/src/data/auth/sagas.js
  packages/blockchain-wallet-v4-frontend/src/data/auth/selectors.js
  packages/blockchain-wallet-v4-frontend/src/data/cache/actionTypes.js
  packages/blockchain-wallet-v4-frontend/src/data/cache/actions.js
  packages/blockchain-wallet-v4-frontend/src/data/cache/reducers.js
  packages/blockchain-wallet-v4-frontend/src/data/cache/selectors.js
  packages/blockchain-wallet-v4-frontend/src/data/middleware/webSocket/coins/actionTypes.js
  packages/blockchain-wallet-v4-frontend/src/data/middleware/webSocket/coins/actions.js
  packages/blockchain-wallet-v4-frontend/src/data/middleware/webSocket/coins/sagaRegister.js
  packages/blockchain-wallet-v4-frontend/src/data/middleware/webSocket/coins/sagas.js
  packages/blockchain-wallet-v4-frontend/src/layouts/Public/index.js
  packages/blockchain-wallet-v4-frontend/src/scenes/Login/index.tsx
  packages/blockchain-wallet-v4-frontend/src/scenes/Login/template.tsx
  packages/blockchain-wallet-v4/src/network/api/wallet/index.ts
  packages/blockchain-wallet-v4/src/redux/data/misc/actionTypes.ts
  packages/blockchain-wallet-v4/src/redux/data/misc/actions.ts
  packages/blockchain-wallet-v4/src/redux/data/misc/sagaRegister.ts
  packages/blockchain-wallet-v4/src/redux/data/misc/sagas.ts
  packages/blockchain-wallet-v4/src/redux/walletOptions/selectors.ts
  packages/blockchain-wallet-v4/src/walletCrypto/index.spec.js
  packages/blockchain-wallet-v4/src/walletCrypto/index.ts
  packages/blockchain-wallet-v4/src/walletCrypto/utils.js
  yarn.lock
Labels: don't merge yet, testing needed, work in progress
